"""
Report generation views.
PDF generation uses ReportLab; Excel uses openpyxl.
Both are lazy-imported so the app works even if not installed
(the error is surfaced at report request time, not import time).
"""
import io
import json
from datetime import date

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.http import HttpResponse

from shared.permissions import IsAnalystOrAbove, IsPartnerOrAbove


def _get_pdf_bytes(content_lines):
    """Simple PDF builder. Replace with full template in production."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.pdfgen import canvas

        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=A4)
        y = 800
        for line in content_lines:
            c.drawString(50, y, line)
            y -= 18
            if y < 50:
                c.showPage()
                y = 800
        c.save()
        return buffer.getvalue()
    except ImportError:
        return b'%PDF-1.4 (ReportLab not installed)'


class FarmerCreditReportView(APIView):
    """Generate individual farmer credit PDF."""
    permission_classes = [IsPartnerOrAbove]

    def post(self, request, farmer_id):
        from apps.farmers.models import FarmerProfile
        from apps.scoring.models import FarmerScore
        from apps.loans.models import LoanCeilingCalculation

        try:
            farmer = FarmerProfile.objects.select_related('group').get(pk=farmer_id)
        except FarmerProfile.DoesNotExist:
            return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)

        score = FarmerScore.objects.filter(farmer=farmer).order_by('-calculated_at').first()
        loan = LoanCeilingCalculation.objects.filter(farmer=farmer).order_by('-calculated_at').first()

        lines = [
            f'AgriProfile Credit Report — {date.today()}',
            '=' * 60,
            f'Name:           {farmer.full_name}',
            f'National ID:    {farmer.national_id}',
            f'Group:          {farmer.group.name}',
            f'District:       {farmer.district}',
            '',
            'AGRIPROFILE CREDIT SCORE (ACS)',
            f'ACS Score:      {float(score.acs_with_saf) if score else "Not calculated"}',
            f'Credit Band:    {score.credit_band.upper() if score else "N/A"}',
            '',
            'LOAN CEILING RECOMMENDATION',
            f'Loan Ceiling:   UGX {int(loan.loan_ceiling_ugx):,}' if loan else 'Not calculated',
            f'Disbursement:   Month {loan.disbursement_month}' if loan else '',
            f'Repayment:      Month {loan.repayment_start_month}' if loan else '',
            '',
            'Generated by AgriProfile — BAHMARK Group',
        ]

        pdf_bytes = _get_pdf_bytes(lines)
        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="credit-report-{farmer_id}.pdf"'
        return response


class GroupCreditReportView(APIView):
    """Generate group credit profile PDF."""
    permission_classes = [IsPartnerOrAbove]

    def post(self, request, group_id):
        from apps.groups.models import FarmerGroup
        from apps.scoring.models import GroupScore

        try:
            group = FarmerGroup.objects.get(pk=group_id)
        except FarmerGroup.DoesNotExist:
            return Response({'detail': 'Not found.'}, status=status.HTTP_404_NOT_FOUND)

        gacs = GroupScore.objects.filter(group=group).order_by('-calculated_at').first()

        lines = [
            f'Group Credit Profile — {date.today()}',
            '=' * 60,
            f'Group:          {group.name}',
            f'Type:           {group.group_type}',
            f'District:       {group.district}',
            f'Members:        {group.member_count}',
            f'Total Land:     {float(group.total_land_acres):.2f} acres',
            '',
            'GROUP AGRIPROFILE CREDIT SCORE (GACS)',
            f'GACS Score:     {float(gacs.gacs_score) if gacs else "Not calculated"}',
            f'Credit Band:    {gacs.credit_band.upper() if gacs else "N/A"}',
            '',
            'Generated by AgriProfile — BAHMARK Group',
        ]

        pdf_bytes = _get_pdf_bytes(lines)
        response = HttpResponse(pdf_bytes, content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="group-profile-{group_id}.pdf"'
        return response


class CropIntelligenceExportView(APIView):
    """Export crop intelligence data as Excel."""
    permission_classes = [IsAnalystOrAbove]

    def get(self, request):
        try:
            import openpyxl
        except ImportError:
            return Response({'detail': 'openpyxl not installed.'}, status=500)

        from apps.farmers.models import FarmerCrop
        from django.db.models import Count, Sum

        crops = (
            FarmerCrop.objects
            .values('crop_name', 'season', 'crop_category', 'sell_to')
            .annotate(farmer_count=Count('farmer', distinct=True), total_acres=Sum('acreage'))
            .order_by('-total_acres')
        )

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = 'Crop Intelligence'
        ws.append(['Crop Name', 'Season', 'Category', 'Market', 'Farmers', 'Total Acres'])
        for row in crops:
            ws.append([
                row['crop_name'], row['season'], row['crop_category'],
                row['sell_to'], row['farmer_count'], float(row['total_acres'] or 0),
            ])

        buffer = io.BytesIO()
        wb.save(buffer)
        buffer.seek(0)

        response = HttpResponse(
            buffer.getvalue(),
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        )
        response['Content-Disposition'] = 'attachment; filename="crop-intelligence.xlsx"'
        return response


class UnbankedFarmersExportView(APIView):
    """Export list of farmers without formal financial accounts."""
    permission_classes = [IsPartnerOrAbove]

    def get(self, request):
        try:
            import openpyxl
        except ImportError:
            return Response({'detail': 'openpyxl not installed.'}, status=500)

        from apps.farmers.models import FarmerProfile

        farmers = FarmerProfile.objects.filter(
            bank_account='', mobile_money_provider='', is_active=True
        ).select_related('group')

        wb = openpyxl.Workbook()
        ws = wb.active
        ws.title = 'Unbanked Farmers'
        ws.append(['Name', 'National ID', 'Phone', 'District', 'Group', 'Gender'])
        for f in farmers:
            ws.append([
                f.full_name, f.national_id, f.primary_phone,
                f.district, f.group.name, f.gender,
            ])

        buffer = io.BytesIO()
        wb.save(buffer)
        buffer.seek(0)

        response = HttpResponse(
            buffer.getvalue(),
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        )
        response['Content-Disposition'] = 'attachment; filename="unbanked-farmers.xlsx"'
        return response
